version: "3.8"

services:
  frontend:
    container_name: local.frontend
    build:
      context: .
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    command: sh -c "yarn install && yarn start"
